# Generated by Django 4.1.7 on 2023-03-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_director_alter_movie_budget_alter_movie_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
